jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    ${{ if or(eq(parameters.name, 'Alpine'), eq(parameters.name, 'CentOS7')) }}:
      container: ${{ parameters.container }}
    strategy:
      matrix:
        node_10_x:
          node_version: 10.x
          publish_artifacts: false
        node_12_x:
          node_version: 12.x
          publish_artifacts: true
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: "Install Node.js"

      - script: npm install --build-from-source
        displayName: Install dependencies
      - script: npm compile
        displayName: Compile and Generate Typings
      - script: npm test
        displayName: Run tests
      - script: npm run prebuild
        displayName: Test prebuild

      - task: PublishBuildArtifacts@1
        displayName: Publish Artifacts
        condition: and(succeeded(), eq(variables['publish_artifacts'], 'true'))
        inputs:
          artifactName: prebuilds
          pathtoPublish: "$(System.DefaultWorkingDirectory)/prebuilds"
